genesis-file="/opt/besu/genesis.json"
data-path="/opt/besu/data"
node-private-key-file="/opt/besu/key"
rpc-http-enabled=true
rpc-http-api=["ETH","QBFT","WEB3", "DEBUG"]
host-allowlist=["*"]
rpc-http-cors-origins=["all"]
tx-pool="legacy"
tx-pool-limit-by-account-percentage=1.0
tx-pool-max-size="1000000"
min-gas-price=0
rpc-ws-enabled=true
rpc-ws-api=["ETH","QBFT","WEB3", "DEBUG"]
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546